<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AppBundle/proto/example.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>SearchRequest</code>
 */
class SearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string query = 1;</code>
     */
    private $query = '';
    /**
     * <code>int32 page_number = 2;</code>
     */
    private $page_number = 0;
    /**
     * <code>int32 result_per_page = 3;</code>
     */
    private $result_per_page = 0;

    public function __construct() {
        \GPBMetadata\AppBundle\Proto\Example::initOnce();
        parent::__construct();
    }

    /**
     * <code>string query = 1;</code>
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * <code>string query = 1;</code>
     */
    public function setQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->query = $var;
    }

    /**
     * <code>int32 page_number = 2;</code>
     */
    public function getPageNumber()
    {
        return $this->page_number;
    }

    /**
     * <code>int32 page_number = 2;</code>
     */
    public function setPageNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_number = $var;
    }

    /**
     * <code>int32 result_per_page = 3;</code>
     */
    public function getResultPerPage()
    {
        return $this->result_per_page;
    }

    /**
     * <code>int32 result_per_page = 3;</code>
     */
    public function setResultPerPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->result_per_page = $var;
    }

}

