<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AppBundle/proto/example.proto

namespace GPBMetadata\AppBundle\Proto;

class Example
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a750a1d41707042756e646c652f70726f746f2f6578616d706c652e7072" .
            "6f746f224c0a0d53656172636852657175657374120d0a05717565727918" .
            "012001280912130a0b706167655f6e756d62657218022001280512170a0f" .
            "726573756c745f7065725f70616765180320012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

